### ISSUE TITLE
remove tree log

### ISSUE THREAD

**Issue by morbidrsa** [naota/linux#1]

**Comment by naota** [comment]
FYI, this is a result of the benchmark using dbench on HDD (with dm-linear to exclude conventional zones). Previously, we had more degradation, but now it diminished.

#Clients |with treelog | without treelog
--|--------------|-----------------
1 client |15.4962 MB/s |15.4962 MB/s
32 clients | 132.563 MB/s | 127.52 MB/s

**Comment by naota** [comment]
I have enabled kmemleak during the benchmark. I'll renew the result.

**Comment by naota** [comment]
And, I should have made a big mistake here. I think the "-o notreelog" is not applied to the above result.

Here is the updated result:

#Clients |with treelog | without treelog
--|--------------|-----------------
1 client |15.8369 MB/s |15.39 MB/s
32 clients | 153.509 MB/s | 21.9651 MB/s

So, we actually have ~85% degradation.
