### ISSUE TITLE
make sure zone reset error is checked

### ISSUE THREAD

**Issue by naota** [naota/linux#13]

**Comment by morbidrsa** [comment]
Resets from:
- [ ] sb_log_location()
- [ ]  btrfs_reset_device_zone()
- [ ] btrfs_reset_sb_log_zones()

**Comment by morbidrsa** [comment]
I've checked all 1st and 2nd level callers of blkdev_zone_mgmt(, REQ_OP_ZONE_RESET, ) and errors get handled there.
