### ISSUE TITLE
Load and pass (on-stack) bgi to read_one_block_group

### ISSUE THREAD

**Issue by naota** [naota/linux#17]
https://patchwork.kernel.org/project/linux-btrfs/patch/8fa3073375cf26759f9c5d3ce083c64d573ad9a6.1608608848.git.naohiro.aota@wdc.com/#23886869

We can "read in the bgi into the stack, and pass the pointer into read_one_block_group(), drop the path before calling read_one_block_group"

**Comment by morbidrsa** [comment]
Fixed locally.
