### ISSUE TITLE
fsck failure with btrfs/209

### ISSUE THREAD

**Issue by morbidrsa** [naota/linux#44]
> rapido1:/home/johannes/src/xfstests-dev# cat results/btrfs/209.full 
> btrfs-progs v5.12.1                                       
> See http://btrfs.wiki.kernel.org for more information.                      
>                                                                                            
> Zoned: /dev/nullb1: host-managed device detected, setting zoned feature
> Detected a SSD, turning off metadata duplication.  Mkfs with -m dup if you want to force metadata duplication.
> Resetting device zones /dev/nullb1 (25 zones) ...
> Label:              (null)
> UUID:               aea6e485-406d-4d65-b8f5-1f6b4ecc401c
> Node size:          16384
> Sector size:        4096
> Filesystem size:    6.25GiB
> Block group profiles:
>   Data:             single          256.00MiB
>   Metadata:         single          256.00MiB
>   System:           single          256.00MiB
> SSD detected:       yes
> Zoned device:       yes
>   Zone size:        256.00MiB
> Incompat features:  extref, skinny-metadata, zoned
> Runtime features:   
> Checksum:           crc32c
> Number of devices:  1
> Devices:
>    ID        SIZE  PATH
>     1     6.25GiB  /dev/nullb1
> 
> btrfs-progs v5.12.1 
> log root tree
> leaf 1342210048 items 1 free space 15819 generation 7 owner TREE_LOG
> leaf 1342210048 flags 0x1(WRITTEN) backref revision 1
> fs uuid aea6e485-406d-4d65-b8f5-1f6b4ecc401c
> chunk uuid 9c089ab2-8ef9-444c-b60c-0eb0bc60d4e5
>         item 0 key (TREE_LOG ROOT_ITEM 5) itemoff 15844 itemsize 439
>                 generation 7 root_dirid 0 bytenr 1342193664 level 0 refs 0
>                 lastsnap 0 byte_limit 0 bytes_used 0 flags 0x0(none)
>                 uuid 00000000-0000-0000-0000-000000000000
>                 drop key (0 UNKNOWN.0 0) level 0
> _check_btrfs_filesystem: filesystem on /dev/nullb1 is inconsistent
> *** fsck.btrfs output ***
> [1/7] checking root items
> [2/7] checking extents
> Extent back ref already exists for 1074790400 parent 0 root 5 owner 257 offset 786432 num_refs 1
> extent item 1074790400 has multiple extent items
> ref mismatch on [1074790400 126976] extent item 1, found 2
> data backref 1074790400 root 5 owner 257 offset 786432 num_refs 0 not found in extent tree
> incorrect local backref count on 1074790400 root 5 owner 257 offset 786432 found 1 wanted 0 back 0x1b3c140
> backref bytes do not match extent backref, bytenr=1074790400, ref bytes=126976, backref bytes=262144
> backpointer mismatch on [1074790400 126976]
> ERROR: errors found in extent allocation tree or chunk allocation
> [3/7] checking free space cache
> [4/7] checking fs roots
> [5/7] checking only csums items (without verifying data)
> [6/7] checking root refs
> [7/7] checking quota groups skipped (not enabled on this FS)
> Opening filesystem to check...
> Checking filesystem on /dev/nullb1
> UUID: aea6e485-406d-4d65-b8f5-1f6b4ecc401c
> found 1282048 bytes used, error(s) found
> total csum bytes: 1024
> total tree bytes: 131072
> total fs tree bytes: 32768
> total extent tree bytes: 16384
> btree space waste bytes: 122165
> file data blocks allocated: 1413120
>  referenced 1048576
> *** end fsck.btrfs output
> *** mount output ***
> rootfs on / type rootfs (rw,size=12249144k,nr_inodes=3062286)
> proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
> sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
> devtmpfs on /dev type devtmpfs (rw,nosuid,noexec,size=12249156k,nr_inodes=3062289,mode=755)
> devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
> tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,noexec)
> tmpfs on /run type tmpfs (rw,nosuid,nodev,noexec,mode=755)
> host0 on /host type 9p (rw,relatime,sync,dirsync,access=client,trans=virtio)
> debugfs on /sys/kernel/debug type debugfs (rw,relatime)
> configfs on /sys/kernel/config type configfs (rw,relatime)
> *** end mount output
>

**Comment by morbidrsa** [comment]
Log of btrfs/209 on a regular FS (succeeding):

> rapido2:/home/johannes/src/xfstests-dev# cat results/btrfs/209.dmesg 
> [  242.288944] run fstests btrfs/209 at 2021-05-19 12:35:04
> [  242.526635] BTRFS: device fsid 59ac917c-4837-411a-9277-30b2c575a211 devid 1 transid 5 /dev/zram1 scanned by mkfs.btrfs (667)
> [  242.546512] BTRFS info (device dm-0): disk space caching is enabled
> [  242.546516] BTRFS info (device dm-0): has skinny extents
> [  242.546517] BTRFS info (device dm-0): flagging fs with big metadata feature
> [  242.548662] BTRFS info (device dm-0): enabling ssd optimizations
> [  242.548770] BTRFS info (device dm-0): checking UUID tree
> [  242.552494] btrfs_sync_file: ino: 257, start: 0, end: 9223372036854775807, datasync: 0
> [  242.552515] btrfs_drop_extent_cache: ino: 257, start: 0, end: 262143
> [  242.552532] create_io_em: ino: 257, em->start: 0, em->orig_start: 0, em->block_start: 13631488, em->len: 262144, em->block_len: 262144
> [  242.552535] btrfs_drop_extent_cache: ino: 257, start: 0, end: 262143
> [  242.552889] btrfs_sync_file: calling btrfs_wait_ordered_range(257, 0, 9223372036854775808)
> [  242.560200] btrfs_drop_extent_cache: ino: 257, start: 262144, end: 1048575
> [  242.560218] create_io_em: ino: 257, em->start: 262144, em->orig_start: 262144, em->block_start: 13893632, em->len: 786432, em->block_len: 786432
> [  242.560220] btrfs_drop_extent_cache: ino: 257, start: 262144, end: 1048575
> [  242.564724] btrfs_sync_file: ino: 257, start: 786432, end: 1048575, datasync: 1
> [  242.564737] btrfs_drop_extent_cache: ino: 257, start: 786432, end: 1048575
> [  242.564743] btrfs_drop_extent_cache: ino: 257, em->start: 262144, em->orig_start: 262144, em->block_start: 13893632, em->len: 786432, em->block_len: 786432
> [  242.564753] create_io_em: ino: 257, em->start: 786432, em->orig_start: 786432, em->block_start: 14680064, em->len: 262144, em->block_len: 262144
> [  242.564754] btrfs_drop_extent_cache: ino: 257, start: 786432, end: 1048575
> [  242.565081] btrfs_log_changed_extents: ino: 257, add em->start: 786432, em->block_start: 14680064, em->len: 262144
> [  242.565085] btrfs_log_changed_extents: ino: 257, add em->start: 262144, em->block_start: 13893632, em->len: 524288
> [  242.565087] log_one_extent: ino: 257, disk_bytenr: 13893632, em->start: 262144, em->block_start: 13893632, em->orig_start: 262144, em->len: 524288, block_len: 786432
> [  242.565101] log_one_extent: ino: 257, disk_bytenr: 13893632, nr: 786432
> [  242.565103] log_one_extent: ino: 257, disk_bytenr: 14680064, em->start: 786432, em->block_start: 14680064, em->orig_start: 786432, em->len: 262144, block_len: 262144
> [  242.565108] log_one_extent: ino: 257, disk_bytenr: 14680064, nr: 262144
> [  242.598549] btrfs_drop_extent_cache: ino: 256, start: 0, end: 18446744073709551615
> [  242.598652] btrfs_drop_extent_cache: ino: 257, start: 0, end: 18446744073709551615
> [  242.599301] btrfs_drop_extent_cache: ino: 1, start: 0, end: 18446744073709551615
> [  242.623494] BTRFS info (device dm-0): disk space caching is enabled
> [  242.623497] BTRFS info (device dm-0): has skinny extents
> [  242.625239] BTRFS info (device dm-0): enabling ssd optimizations
> [  242.625242] BTRFS info (device dm-0): start tree-log replay
> [  242.625554] btrfs_drop_extent_cache: ino: 257, start: 1048576, end: 18446744073709551614
> [  242.625569] btrfs_drop_extent_cache: ino: 257, start: 0, end: 18446744073709551615
> [  242.625590] btrfs_drop_extent_cache: ino: 257, start: 0, end: 18446744073709551615
> [  242.625625] btrfs_drop_extent_cache: ino: 257, start: 262144, end: 786431
> [  242.625728] btrfs_drop_extent_cache: ino: 257, start: 0, end: 18446744073709551615
> [  242.625745] btrfs_drop_extent_cache: ino: 257, start: 786432, end: 1048575
> [  242.625775] btrfs_drop_extent_cache: ino: 257, start: 0, end: 18446744073709551615
> [  242.625800] btrfs_drop_extent_cache: ino: 257, start: 0, end: 18446744073709551615
> [  242.634959] btrfs_drop_extent_cache: ino: 256, start: 0, end: 18446744073709551615
> [  242.635048] btrfs_drop_extent_cache: ino: 257, start: 0, end: 18446744073709551615
> [  242.635684] btrfs_drop_extent_cache: ino: 1, start: 0, end: 18446744073709551615
> [  242.665910] btrfs_drop_extent_cache: ino: 256, start: 0, end: 18446744073709551615
> [  242.666885] btrfs_drop_extent_cache: ino: 1, start: 0, end: 18446744073709551615
> rapido2:/home/johannes/src/xfstests-dev#

**Comment by morbidrsa** [comment]
Failure log on zoned btrfs:

> rapido1:/home/johannes/src/xfstests-dev# cat results/btrfs/209.dmesg             
> [   54.312535] run fstests btrfs/209 at 2021-05-19 12:38:41                      
> [   54.579324] BTRFS: device fsid 2a04398e-74e5-468d-99fd-4ad39bcd4edb devid 1 transid 5 /dev/nullb1 scanned by mkfs.btrfs (659)
> [   54.601112] BTRFS info (device dm-0): has skinny extents                      
> [   54.601116] BTRFS info (device dm-0): flagging fs with big metadata feature   
> [   54.602558] BTRFS info (device dm-0): host-managed zoned block device /dev/mapper/flakey-test, 25 zones of 268435456 bytes
> [   54.602575] BTRFS info (device dm-0): zoned mode enabled with zone size 268435456
> [   54.603167] BTRFS info (device dm-0): enabling ssd optimizations              
> [   54.603292] BTRFS info (device dm-0): checking UUID tree                      
> [   54.607078] btrfs_sync_file: ino: 257, start: 0, end: 9223372036854775807, datasync: 0
> [   54.607097] btrfs_drop_extent_cache: ino: 257, start: 0, end: 262143          
> [   54.607112] create_io_em: ino: 257, em->start: 0, em->orig_start: 0, em->block_start: 1073741824, em->len: 262144, em->block_len: 262144
> [   54.607115] btrfs_drop_extent_cache: ino: 257, start: 0, end: 262143          
> [   54.607173] create_io_em: ino: 257, em->start: 0, em->orig_start: 0, em->block_start: 1073741824, em->len: 126976, em->block_len: 126976
> [   54.607176] btrfs_drop_extent_cache: ino: 257, start: 0, end: 126975          
> [   54.607184] btrfs_drop_extent_cache: ino: 257, em->start: 0, em->orig_start: 0, em->block_start: 1073741824, em->len: 262144, em->block_len: 262144
> [   54.607186] btrfs_drop_extent_cache:659 ino: 257, split->start: 126976, split->orig_start: 0, split->block_start: 1073868800, split->len: 135168, split->block_len: 135168, diff: 126976, em_in_tree: 0
> [   54.607360] create_io_em: ino: 257, em->start: 126976, em->orig_start: 126976, em->block_start: 1073868800, em->len: 126976, em->block_len: 126976
> [   54.607362] btrfs_drop_extent_cache: ino: 257, start: 126976, end: 253951     
> [   54.607370] btrfs_drop_extent_cache: ino: 257, em->start: 126976, em->orig_start: 0, em->block_start: 1073868800, em->len: 135168, em->block_len: 135168
> [   54.607372] btrfs_drop_extent_cache:659 ino: 257, split->start: 253952, split->orig_start: 0, split->block_start: 1073995776, split->len: 8192, split->block_len: 8192, diff: 126976, em_in_tree: 0
> [   54.607818] btrfs_sync_file: calling btrfs_wait_ordered_range(257, 0, 9223372036854775808)
> [   54.615379] btrfs_drop_extent_cache: ino: 257, start: 262144, end: 1048575    
> [   54.615396] create_io_em: ino: 257, em->start: 262144, em->orig_start: 262144, em->block_start: 1074003968, em->len: 786432, em->block_len: 786432
> [   54.615399] btrfs_drop_extent_cache: ino: 257, start: 262144, end: 1048575    
> [   54.615458] create_io_em: ino: 257, em->start: 262144, em->orig_start: 262144, em->block_start: 1074003968, em->len: 126976, em->block_len: 126976
> [   54.615461] btrfs_drop_extent_cache: ino: 257, start: 262144, end: 389119     
> [   54.615469] btrfs_drop_extent_cache: ino: 257, em->start: 262144, em->orig_start: 262144, em->block_start: 1074003968, em->len: 786432, em->block_len: 786432
> [   54.615472] btrfs_drop_extent_cache:659 ino: 257, split->start: 389120, split->orig_start: 262144, split->block_start: 1074130944, split->len: 659456, split->block_len: 659456, diff: 126976, em_in_tree: 0
> [   54.615516] create_io_em: ino: 257, em->start: 389120, em->orig_start: 389120, em->block_start: 1074130944, em->len: 126976, em->block_len: 126976
> [   54.615518] btrfs_drop_extent_cache: ino: 257, start: 389120, end: 516095     
> [   54.615526] btrfs_drop_extent_cache: ino: 257, em->start: 389120, em->orig_start: 262144, em->block_start: 1074130944, em->len: 659456, em->block_len: 659456
> [   54.615528] btrfs_drop_extent_cache:659 ino: 257, split->start: 516096, split->orig_start: 262144, split->block_start: 1074257920, split->len: 532480, split->block_len: 532480, diff: 126976, em_in_tree: 0
> [   54.615567] create_io_em: ino: 257, em->start: 516096, em->orig_start: 516096, em->block_start: 1074257920, em->len: 126976, em->block_len: 126976
> [   54.615569] btrfs_drop_extent_cache: ino: 257, start: 516096, end: 643071     
> [   54.615576] btrfs_drop_extent_cache: ino: 257, em->start: 516096, em->orig_start: 262144, em->block_start: 1074257920, em->len: 532480, em->block_len: 532480
> [   54.615578] btrfs_drop_extent_cache:659 ino: 257, split->start: 643072, split->orig_start: 262144, split->block_start: 1074384896, split->len: 405504, split->block_len: 405504, diff: 126976, em_in_tree: 0
> [   54.615618] create_io_em: ino: 257, em->start: 643072, em->orig_start: 643072, em->block_start: 1074384896, em->len: 126976, em->block_len: 126976
> [   54.615620] btrfs_drop_extent_cache: ino: 257, start: 643072, end: 770047     
> [   54.615627] btrfs_drop_extent_cache: ino: 257, em->start: 643072, em->orig_start: 262144, em->block_start: 1074384896, em->len: 405504, em->block_len: 405504
> [   54.615629] btrfs_drop_extent_cache:659 ino: 257, split->start: 770048, split->orig_start: 262144, split->block_start: 1074511872, split->len: 278528, split->block_len: 278528, diff: 126976, em_in_tree: 0
> [   54.615676] create_io_em: ino: 257, em->start: 770048, em->orig_start: 770048, em->block_start: 1074511872, em->len: 126976, em->block_len: 126976
> [   54.615678] btrfs_drop_extent_cache: ino: 257, start: 770048, end: 897023     
> [   54.615685] btrfs_drop_extent_cache: ino: 257, em->start: 770048, em->orig_start: 262144, em->block_start: 1074511872, em->len: 278528, em->block_len: 278528
> [   54.615687] btrfs_drop_extent_cache:659 ino: 257, split->start: 897024, split->orig_start: 262144, split->block_start: 1074638848, split->len: 151552, split->block_len: 151552, diff: 126976, em_in_tree: 0
> [   54.615728] create_io_em: ino: 257, em->start: 897024, em->orig_start: 897024, em->block_start: 1074638848, em->len: 126976, em->block_len: 126976
> [   54.615730] btrfs_drop_extent_cache: ino: 257, start: 897024, end: 1023999    
> [   54.615738] btrfs_drop_extent_cache: ino: 257, em->start: 897024, em->orig_start: 262144, em->block_start: 1074638848, em->len: 151552, em->block_len: 151552
> [   54.615740] btrfs_drop_extent_cache:659 ino: 257, split->start: 1024000, split->orig_start: 262144, split->block_start: 1074765824, split->len: 24576, split->block_len: 24576, diff: 126976, em_in_tree: 0
> [   54.620630] btrfs_sync_file: ino: 257, start: 786432, end: 1048575, datasync: 1
> [   54.620647] btrfs_drop_extent_cache: ino: 257, start: 786432, end: 1048575    
> [   54.620656] btrfs_drop_extent_cache: ino: 257, em->start: 770048, em->orig_start: 770048, em->block_start: 1074511872, em->len: 126976, em->block_len: 126976
> [   54.620663] btrfs_drop_extent_cache: ino: 257, em->start: 897024, em->orig_start: 897024, em->block_start: 1074638848, em->len: 126976, em->block_len: 126976
> [   54.620665] btrfs_drop_extent_cache: ino: 257, em->start: 1024000, em->orig_start: 262144, em->block_start: 1074765824, em->len: 24576, em->block_len: 24576
> [   54.620672] create_io_em: ino: 257, em->start: 786432, em->orig_start: 786432, em->block_start: 1074790400, em->len: 262144, em->block_len: 262144
> [   54.620674] btrfs_drop_extent_cache: ino: 257, start: 786432, end: 1048575    
> [   54.620756] create_io_em: ino: 257, em->start: 786432, em->orig_start: 786432, em->block_start: 1074790400, em->len: 126976, em->block_len: 126976
> [   54.620758] btrfs_drop_extent_cache: ino: 257, start: 786432, end: 913407     
> [   54.620765] btrfs_drop_extent_cache: ino: 257, em->start: 786432, em->orig_start: 786432, em->block_start: 1074790400, em->len: 262144, em->block_len: 262144
> [   54.620767] btrfs_drop_extent_cache:659 ino: 257, split->start: 913408, split->orig_start: 786432, split->block_start: 1074917376, split->len: 135168, split->block_len: 135168, diff: 126976, em_in_tree: 0
> [   54.621094] create_io_em: ino: 257, em->start: 913408, em->orig_start: 913408, em->block_start: 1074917376, em->len: 126976, em->block_len: 126976
> [   54.621096] btrfs_drop_extent_cache: ino: 257, start: 913408, end: 1040383    
> [   54.621103] btrfs_drop_extent_cache: ino: 257, em->start: 913408, em->orig_start: 786432, em->block_start: 1074917376, em->len: 135168, em->block_len: 135168
> [   54.621105] btrfs_drop_extent_cache:659 ino: 257, split->start: 1040384, split->orig_start: 786432, split->block_start: 1075044352, split->len: 8192, split->block_len: 8192, diff: 126976, em_in_tree: 0
> [   54.621469] btrfs_sync_file: calling btrfs_wait_ordered_range(257, 0, 9223372036854775808)
> rapido1:/home/johannes/src/xfstests-dev# cat results/btrfs/209.dmesg             
> [   54.312535] run fstests btrfs/209 at 2021-05-19 12:38:41                      
> [   54.579324] BTRFS: device fsid 2a04398e-74e5-468d-99fd-4ad39bcd4edb devid 1 transid 5 /dev/nullb1 scanned by mkfs.btrfs (659)
> [   54.601112] BTRFS info (device dm-0): has skinny extents                      
> [   54.601116] BTRFS info (device dm-0): flagging fs with big metadata feature   
> [   54.602558] BTRFS info (device dm-0): host-managed zoned block device /dev/mapper/flakey-test, 25 zones of 268435456 bytes
> [   54.602575] BTRFS info (device dm-0): zoned mode enabled with zone size 268435456
> [   54.603167] BTRFS info (device dm-0): enabling ssd optimizations              
> [   54.603292] BTRFS info (device dm-0): checking UUID tree                      
> [   54.607078] btrfs_sync_file: ino: 257, start: 0, end: 9223372036854775807, datasync: 0
> [   54.607097] btrfs_drop_extent_cache: ino: 257, start: 0, end: 262143          
> [   54.607112] create_io_em: ino: 257, em->start: 0, em->orig_start: 0, em->block_start: 1073741824, em->len: 262144, em->block_len: 262144
> [   54.607115] btrfs_drop_extent_cache: ino: 257, start: 0, end: 262143          
> [   54.607173] create_io_em: ino: 257, em->start: 0, em->orig_start: 0, em->block_start: 1073741824, em->len: 126976, em->block_len: 126976
> [   54.607176] btrfs_drop_extent_cache: ino: 257, start: 0, end: 126975          
> [   54.607184] btrfs_drop_extent_cache: ino: 257, em->start: 0, em->orig_start: 0, em->block_start: 1073741824, em->len: 262144, em->block_len: 262144
> [   54.607186] btrfs_drop_extent_cache:659 ino: 257, split->start: 126976, split->orig_start: 0, split->block_start: 1073868800, split->len: 135168, split->block_len: 135168, diff: 126976, em_in_tree: 0
> [   54.607360] create_io_em: ino: 257, em->start: 126976, em->orig_start: 126976, em->block_start: 1073868800, em->len: 126976, em->block_len: 126976
> [   54.607362] btrfs_drop_extent_cache: ino: 257, start: 126976, end: 253951     
> [   54.607370] btrfs_drop_extent_cache: ino: 257, em->start: 126976, em->orig_start: 0, em->block_start: 1073868800, em->len: 135168, em->block_len: 135168
> [   54.607372] btrfs_drop_extent_cache:659 ino: 257, split->start: 253952, split->orig_start: 0, split->block_start: 1073995776, split->len: 8192, split->block_len: 8192, diff: 126976, em_in_tree: 0
> [   54.607818] btrfs_sync_file: calling btrfs_wait_ordered_range(257, 0, 9223372036854775808)
> [   54.615379] btrfs_drop_extent_cache: ino: 257, start: 262144, end: 1048575    
> [   54.615396] create_io_em: ino: 257, em->start: 262144, em->orig_start: 262144, em->block_start: 1074003968, em->len: 786432, em->block_len: 786432
> [   54.615399] btrfs_drop_extent_cache: ino: 257, start: 262144, end: 1048575    
> [   54.615458] create_io_em: ino: 257, em->start: 262144, em->orig_start: 262144, em->block_start: 1074003968, em->len: 126976, em->block_len: 126976
> [   54.615461] btrfs_drop_extent_cache: ino: 257, start: 262144, end: 389119     
> [   54.615469] btrfs_drop_extent_cache: ino: 257, em->start: 262144, em->orig_start: 262144, em->block_start: 1074003968, em->len: 786432, em->block_len: 786432
> [   54.615472] btrfs_drop_extent_cache:659 ino: 257, split->start: 389120, split->orig_start: 262144, split->block_start: 1074130944, split->len: 659456, split->block_len: 659456, diff: 126976, em_in_tree: 0
> [   54.615516] create_io_em: ino: 257, em->start: 389120, em->orig_start: 389120, em->block_start: 1074130944, em->len: 126976, em->block_len: 126976
> [   54.615518] btrfs_drop_extent_cache: ino: 257, start: 389120, end: 516095     
> [   54.615526] btrfs_drop_extent_cache: ino: 257, em->start: 389120, em->orig_start: 262144, em->block_start: 1074130944, em->len: 659456, em->block_len: 659456
> [   54.615528] btrfs_drop_extent_cache:659 ino: 257, split->start: 516096, split->orig_start: 262144, split->block_start: 1074257920, split->len: 532480, split->block_len: 532480, diff: 126976, em_in_tree: 0
> [   54.615567] create_io_em: ino: 257, em->start: 516096, em->orig_start: 516096, em->block_start: 1074257920, em->len: 126976, em->block_len: 126976
> [   54.615569] btrfs_drop_extent_cache: ino: 257, start: 516096, end: 643071     
> [   54.615576] btrfs_drop_extent_cache: ino: 257, em->start: 516096, em->orig_start: 262144, em->block_start: 1074257920, em->len: 532480, em->block_len: 532480
> [   54.615578] btrfs_drop_extent_cache:659 ino: 257, split->start: 643072, split->orig_start: 262144, split->block_start: 1074384896, split->len: 405504, split->block_len: 405504, diff: 126976, em_in_tree: 0
> [   54.615618] create_io_em: ino: 257, em->start: 643072, em->orig_start: 643072, em->block_start: 1074384896, em->len: 126976, em->block_len: 126976
> [   54.615620] btrfs_drop_extent_cache: ino: 257, start: 643072, end: 770047     
> [   54.615627] btrfs_drop_extent_cache: ino: 257, em->start: 643072, em->orig_start: 262144, em->block_start: 1074384896, em->len: 405504, em->block_len: 405504
> [   54.615629] btrfs_drop_extent_cache:659 ino: 257, split->start: 770048, split->orig_start: 262144, split->block_start: 1074511872, split->len: 278528, split->block_len: 278528, diff: 126976, em_in_tree: 0
> [   54.615676] create_io_em: ino: 257, em->start: 770048, em->orig_start: 770048, em->block_start: 1074511872, em->len: 126976, em->block_len: 126976
> [   54.615678] btrfs_drop_extent_cache: ino: 257, start: 770048, end: 897023     
> [   54.615685] btrfs_drop_extent_cache: ino: 257, em->start: 770048, em->orig_start: 262144, em->block_start: 1074511872, em->len: 278528, em->block_len: 278528
> [   54.615687] btrfs_drop_extent_cache:659 ino: 257, split->start: 897024, split->orig_start: 262144, split->block_start: 1074638848, split->len: 151552, split->block_len: 151552, diff: 126976, em_in_tree: 0
> [   54.615728] create_io_em: ino: 257, em->start: 897024, em->orig_start: 897024, em->block_start: 1074638848, em->len: 126976, em->block_len: 126976
> [   54.615730] btrfs_drop_extent_cache: ino: 257, start: 897024, end: 1023999    
> [   54.615738] btrfs_drop_extent_cache: ino: 257, em->start: 897024, em->orig_start: 262144, em->block_start: 1074638848, em->len: 151552, em->block_len: 151552
> [   54.615740] btrfs_drop_extent_cache:659 ino: 257, split->start: 1024000, split->orig_start: 262144, split->block_start: 1074765824, split->len: 24576, split->block_len: 24576, diff: 126976, em_in_tree: 0
> [   54.620630] btrfs_sync_file: ino: 257, start: 786432, end: 1048575, datasync: 1
> [   54.620647] btrfs_drop_extent_cache: ino: 257, start: 786432, end: 1048575    
> [   54.620656] btrfs_drop_extent_cache: ino: 257, em->start: 770048, em->orig_start: 770048, em->block_start: 1074511872, em->len: 126976, em->block_len: 126976
> [   54.620663] btrfs_drop_extent_cache: ino: 257, em->start: 897024, em->orig_start: 897024, em->block_start: 1074638848, em->len: 126976, em->block_len: 126976
> [   54.620665] btrfs_drop_extent_cache: ino: 257, em->start: 1024000, em->orig_start: 262144, em->block_start: 1074765824, em->len: 24576, em->block_len: 24576
> [   54.620672] create_io_em: ino: 257, em->start: 786432, em->orig_start: 786432, em->block_start: 1074790400, em->len: 262144, em->block_len: 262144
> [   54.620674] btrfs_drop_extent_cache: ino: 257, start: 786432, end: 1048575    
> [   54.620756] create_io_em: ino: 257, em->start: 786432, em->orig_start: 786432, em->block_start: 1074790400, em->len: 126976, em->block_len: 126976
> [   54.620758] btrfs_drop_extent_cache: ino: 257, start: 786432, end: 913407     
> [   54.620765] btrfs_drop_extent_cache: ino: 257, em->start: 786432, em->orig_start: 786432, em->block_start: 1074790400, em->len: 262144, em->block_len: 262144
> [   54.620767] btrfs_drop_extent_cache:659 ino: 257, split->start: 913408, split->orig_start: 786432, split->block_start: 1074917376, split->len: 135168, split->block_len: 135168, diff: 126976, em_in_tree: 0
> [   54.621094] create_io_em: ino: 257, em->start: 913408, em->orig_start: 913408, em->block_start: 1074917376, em->len: 126976, em->block_len: 126976
> [   54.621096] btrfs_drop_extent_cache: ino: 257, start: 913408, end: 1040383    
> [   54.621103] btrfs_drop_extent_cache: ino: 257, em->start: 913408, em->orig_start: 786432, em->block_start: 1074917376, em->len: 135168, em->block_len: 135168
> [   54.621105] btrfs_drop_extent_cache:659 ino: 257, split->start: 1040384, split->orig_start: 786432, split->block_start: 1075044352, split->len: 8192, split->block_len: 8192, diff: 126976, em_in_tree: 0
> [   54.621469] btrfs_sync_file: calling btrfs_wait_ordered_range(257, 0, 9223372036854775808)

**Comment by morbidrsa** [comment]
https://github.com/btrfs/linux/issues/260

**Comment by naota** [comment]
Patch sent
https://lore.kernel.org/linux-btrfs/20210628085728.2813793-1-naohiro.aota@wdc.com/T/#u

**Comment by morbidrsa** [comment]
https://lore.kernel.org/linux-btrfs/20210628085728.2813793-1-naohiro.aota@wdc.com

**Comment by morbidrsa** [comment]
https://github.com/btrfs/linux/issues/276

**Comment by morbidrsa** [comment]
Fixed with: 7f01d1af172e ("btrfs: properly split extent_map for REQ_OP_ZONE_APPEND")
